# config.yml

OD_DIR: opendata # directory with raw open data
DATA_DIR: data # directory with data (previously parsed by opendata)
OD_FILE_TYPE: csv 
TED_CFC_FILE: TED_CFC_YS-YE.csv # CFC file merged (YS = Yeast Start, YE = Year End -> see TED_CONFIG_FILE)
TED_CFC_SCHEMA_FILE: TED_CFC_schema.csv # CFC file schema (derived from data)
TED_CAN_FILE: TED_CAN_YS-YE.csv # CAN file merged  (YS = Yeast Start, YE = Year End -> see TED_CONFIG_FILE)
TED_CAN_SCHEMA_FILE: TED_CAN_schema.csv # CAN file schema (derived from data)
TED_URLS_FILE: TED_URLs.csv # CFC reference to URL (complete text of CFC)
TED_JOIN_FILE: TED_CFC_CAN_YS-YE.csv # CFC and CAN file merged (input file for creating the event log)
COUNTRY_CODES_FEATURE: ISO_COUNTRY_CODE # Country codes feature name (filter)
TED_LOG_EVENTS: # Features containing events (ID_NOTICE_CN is the case-id, the other columns contain the timestamp so if they are not empty the event has occurred)
  - ID_NOTICE_CN
  - DT_DISPATCH
  - CONTRACT_START
  - CONTRACT_COMPLETION
  - DT_APPLICATIONS
  - DT_AWARD
TED_LOG_ATTRIBUTES: # Features containing trace attributes
  - TYPE_OF_CONTRACT
  - VALUE_EURO
  - B_ELECTRONIC_AUCTION
  - B_FRA_AGREEMENT
  - TAL_LOCATION_NUTS
  - CPV
  - ISO_COUNTRY_CODE
LOG_DIR: data_log # directory with event log
LOG_FILE: TED_log_YS-YE.csv # final event log in output (YS = Yeast Start, YE = Year End -> see TED_CONFIG_FILE)
GUUE_DIR: guue
TED_CONFIG_FILE: ted_config.json # Filter configuration JSON feature: [desired values].
STATS_DIR: stats
CPV_DIVISION: 90 # The CPV division is the first two digits of the CPV code
