# config.yml

OD_DIR: opendata # directory with raw open data
DATA_DIR: data # directory with data (previously parsed by opendata)
GUUE_DIR: guue # directory with PDFs downloaded from TED_URLS_FILE
OD_FILE_TYPE: csv 
TED_CFC_FILE: TED_CFC_YS-YE.csv # CFC file merged (YS = Yeast Start, YE = Year End -> see TED_CONFIG_FILE)
TED_CFC_SCHEMA_FILE: TED_CFC_schema.csv # CFC file schema (derived from data)
TED_CAN_FILE: TED_CAN_YS-YE.csv # CAN file merged  (YS = Yeast Start, YE = Year End -> see TED_CONFIG_FILE)
TED_CAN_SCHEMA_FILE: TED_CAN_schema.csv # CAN file schema (derived from data)
TED_URLS_FILE: TED_URLs.csv # CFC reference to URL (complete text of CFC)
TED_JOIN_FILE: TED_CFC_CAN_YS-YE.csv # CFC and CAN file merged (input file for creating the event log)
COUNTRY_CODES_FEATURE: ISO_COUNTRY_CODE # Country codes feature name (filter)
TED_LOG_EVENTS: # Features containing events (ID_NOTICE_CN is the case-id, the other columns contain the timestamp so if they are not empty the event has occurred) (list)
  - ID_NOTICE_CN
  - DT_DISPATCH
  - CONTRACT_START
  - CONTRACT_COMPLETION
  - DT_APPLICATIONS
  - DT_AWARD
TED_LOG_ATTRIBUTES: # Features containing trace attributes (list)
  - TYPE_OF_CONTRACT
  - VALUE_EURO
  - B_ELECTRONIC_AUCTION
  - B_FRA_AGREEMENT
  - TAL_LOCATION_NUTS
  - CPV
  - ISO_COUNTRY_CODE
  - YEAR
LOG_DIR: data_log # directory with event log
LOG_FILE: TED_log_YS-YE.csv # final event log in output (YS = Yeast Start, YE = Year End -> see TED_CONFIG_FILE)
TED_CONFIG_FILE: ted_config_data.json # Filter configuration JSON -> feature: [desired values]
STATS_DIR: stats
CPV_DIVISION: 90 # The CPV division is the first two digits of the CPV code (filter for stats)
TED_CFC_TYPES: # Columns CFC not to be transformed into numbers (dict)
  ID_NOTICE_CN: object
  FUTURE_CAN_ID: object
  FUTURE_CAN_ID_ESTIMATED: object
  CPV: object
  CAE_TYPE: object
TED_CAN_TYPES: # Columns CAN not to be transformed into numbers (dict)
  ID_NOTICE_CAN: object
  ID_AWARD: object
  ID_LOT_AWARDED: object
  CPV: object
  CAE_TYPE: object
TED_LANG_DOWNLOAD: # Language code for downloading PDFs in GUUE_DIR (list) ['DE', 'ES', 'FR', 'IT', 'PT']
  - DE 
TED_CPV_DOWNLOAD:
  - 90
YEAR_START: 2016 # Starting year (included)
YEAR_END: 2022 # End year (included)
LOG_DOWNLOAD: ted_log_pdf_download.csv # Timing download
LOG_DOWNLOAD_HEADER: lang;time_start;time_end;time_delta;num_files